// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO2k28P9I59e8QCxTtTpivckuA44cHQxQ',
    appId: '1:818749241574:web:6ccda088dff8ae859ea327',
    messagingSenderId: '818749241574',
    projectId: 'trashandcash-cef2f',
    authDomain: 'trashandcash-cef2f.firebaseapp.com',
    storageBucket: 'trashandcash-cef2f.firebasestorage.app',
    measurementId: 'G-CQGQDKBGQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRMG1TWZUNsooUErPxEZYUH_qFs7Mh0oA',
    appId: '1:818749241574:android:56697c87611d04309ea327',
    messagingSenderId: '818749241574',
    projectId: 'trashandcash-cef2f',
    storageBucket: 'trashandcash-cef2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrqCANiB1qm9mC-WLI2CV0RLee5ovskY',
    appId: '1:818749241574:ios:6940a7703d7ffa0c9ea327',
    messagingSenderId: '818749241574',
    projectId: 'trashandcash-cef2f',
    storageBucket: 'trashandcash-cef2f.firebasestorage.app',
    iosBundleId: 'com.example.trashCash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmrqCANiB1qm9mC-WLI2CV0RLee5ovskY',
    appId: '1:818749241574:ios:6940a7703d7ffa0c9ea327',
    messagingSenderId: '818749241574',
    projectId: 'trashandcash-cef2f',
    storageBucket: 'trashandcash-cef2f.firebasestorage.app',
    iosBundleId: 'com.example.trashCash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO2k28P9I59e8QCxTtTpivckuA44cHQxQ',
    appId: '1:818749241574:web:e7d510f247a0bfc29ea327',
    messagingSenderId: '818749241574',
    projectId: 'trashandcash-cef2f',
    authDomain: 'trashandcash-cef2f.firebaseapp.com',
    storageBucket: 'trashandcash-cef2f.firebasestorage.app',
    measurementId: 'G-6E42S9NNVZ',
  );
}
